The files train.csv and test.csv contain all the training samples as comma-sparated values. There are 3 columns in them, corresponding to class index (1 to 4), title and description. The title and description are escaped using double quotes ("), and any internal double quote is escaped by 2 double quotes (""). New lines are escaped by a backslash followed with an "n" character, that is "\n".

In [26]:
import pandas as pd 

# load dataset 
train_path= "../data/raw/train.csv"

df=pd.read_csv(train_path)

df.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

02- Data preproceess

In [28]:
df["text"]= df["Title"] + " " + df["Description"]

df["labels"] = df["Class Index"]-1 #pytorch takes indx from 0

df= df[["text","labels"]]
df.head(10)

                                                text  labels
0  Wall St. Bears Claw Back Into the Black (Reute...       2
1  Carlyle Looks Toward Commercial Aerospace (Reu...       2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...       2
3  Iraq Halts Oil Exports from Main Southern Pipe...       2
4  Oil prices soar to all-time record, posing new...       2
5  Stocks End Up, But Near Year Lows (Reuters) Re...       2
6  Money Funds Fell in Latest Week (AP) AP - Asse...       2
7  Fed minutes show dissent over inflation (USATO...       2
8  Safety Net (Forbes.com) Forbes.com - After ear...       2
9  Wall St. Bears Claw Back Into the Black  NEW Y...       2

In [29]:
df["text"] = df["text"].str.replace("\\n", " ", regex=True)
df["text"] = df["text"].str.strip()

C:\Users\apurb_oi8roye\AppData\Local\Temp\ipykernel_3360\3099205216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].str.replace("\\n", " ", regex=True)
C:\Users\apurb_oi8roye\AppData\Local\Temp\ipykernel_3360\3099205216.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].str.strip()

In [30]:

df.head(10)

                                                text  labels
0  Wall St. Bears Claw Back Into the Black (Reute...       2
1  Carlyle Looks Toward Commercial Aerospace (Reu...       2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...       2
3  Iraq Halts Oil Exports from Main Southern Pipe...       2
4  Oil prices soar to all-time record, posing new...       2
5  Stocks End Up, But Near Year Lows (Reuters) Re...       2
6  Money Funds Fell in Latest Week (AP) AP - Asse...       2
7  Fed minutes show dissent over inflation (USATO...       2
8  Safety Net (Forbes.com) Forbes.com - After ear...       2
9  Wall St. Bears Claw Back Into the Black  NEW Y...       2

Tokenising the text now

In [31]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
def tokenize_function(example):
    return tokenizer(
        example,
        padding="max_length",
        truncation=True,
        max_length=128
    )

# apply to all rows
tokenized = df["text"].apply(tokenize_function)

In [32]:
tokenized.iloc[0]

{'input_ids': [101, 2813, 2358, 1012, 6468, 15020, 2067, 2046, 1996, 2304, 1006, 26665, 1007, 26665, 1011, 2460, 1011, 19041, 1010, 2813, 2395, 1005, 1055, 1040, 11101, 2989, 1032, 2316, 1997, 11087, 1011, 22330, 8713, 2015, 1010, 2024, 3773, 2665, 2153, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [8]:
pip install datasets

Collecting datasets
  Using cached datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (2.32.3)
Requirement already satisfied: httpx<1.0.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2024.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (1.4.1)
Requirement already satisfied: packaging in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.11.10)
Requirement already satisfied: anyio in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.7.0)
Requirement already satisfied: certifi in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.2)
Requirement already satisfied: idna in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: shellingham in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer-slim in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: colorama in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: typer>=0.24.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.24.0)
Requirement already satisfied: click>=8.2.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\apurb_oi8roye\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.0)
Using cached datasets-4.8.5-py3-none-any.whl (528 kB)
Installing collected packages: datasets
Successfully installed datasets-4.8.5
Note: you may need to restart the kernel to use updated packages.

In [33]:
from datasets import Dataset

# Convert pandas DataFrame to Dataset, which is compatible for training
dataset = Dataset.from_pandas(df)

def tokenize_function(exm):
    return tokenizer(
        exm["text"],   #  for Dataset
        padding="max_length",
        truncation=True,
        max_length=128
    )

dataset = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/120000 [00:00<?, ? examples/s]

In [34]:
dataset[0]

{'text': "Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.",
 'labels': 2,
 'input_ids': [101,
  2813,
  2358,
  1012,
  6468,
  15020,
  2067,
  2046,
  1996,
  2304,
  1006,
  26665,
  1007,
  26665,
  1011,
  2460,
  1011,
  19041,
  1010,
  2813,
  2395,
  1005,
  1055,
  1040,
  11101,
  2989,
  1032,
  2316,
  1997,
  11087,
  1011,
  22330,
  8713,
  2015,
  1010,
  2024,
  3773,
  2665,
  2153,
  1012,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [35]:
dataset = dataset.remove_columns(["token_type_ids","text"])
dataset.set_format("torch")

In [36]:
dataset.column_names

['labels', 'input_ids', 'attention_mask']

In [37]:
df.to_csv("../data/processed/cleaned.csv", index=False)

In [38]:
dataset.save_to_disk("../data/processed/tokenized_dataset")

Saving the dataset (0/1 shards):   0%|          | 0/120000 [00:00<?, ? examples/s]